"""
AIOps Infrastructure Anomaly Detection Service
================================================
FastAPI application that:
  - Exposes /metrics endpoint for Prometheus scraping
  - Exposes /anomalies endpoint for current anomaly state
  - Runs a background scheduler polling Prometheus every POLL_INTERVAL seconds
  - Applies Z-Score, EWMA, and Isolation Forest detection on each metric
  - Fires alerts to Alertmanager when anomalies are detected
  - Indexes anomaly events to Elasticsearch for historical analysis

Endpoints:
  GET /health/live   — liveness probe
  GET /health/ready  — readiness probe (checks Prometheus connectivity)
  GET /metrics       — Prometheus metrics (auto-generated)
  GET /anomalies     — current anomaly scores and history
  GET /status        — detection loop status and config
"""

import threading
import time
from contextlib import asynccontextmanager
from datetime import UTC, datetime

from fastapi import FastAPI, HTTPException
from prometheus_client import (
    Counter,
    Gauge,
    make_asgi_app,
)

from .alerting import send_alert
from .config import ANOMALY_THRESHOLD, POLL_INTERVAL, PROMETHEUS_URL
from .elasticsearch_client import index_anomaly
from .services.anomaly_service import analyze_metric
from .services.metric_service import fetch_all_metrics
from .utils.logger import get_logger

logger = get_logger(__name__)

# ============================================================================
# Prometheus Metrics
# ============================================================================

ML_ANOMALY_SCORE = Gauge(
    "ml_anomaly_score",
    "Latest anomaly score generated by anomaly detector",
    ["metric", "instance"]
)

ML_ANOMALIES_TOTAL = Counter(
    "ml_anomalies_total",
    "Total number of detected anomalies"
)

ML_MONITORED_SERIES = Gauge(
    "ml_monitored_series",
    "Number of monitored metric time series"
)

# ── In-memory state ───────────────────────────────────────────────────────────
_detection_state: dict = {
    "running":        False,
    "last_run":       None,
    "total_runs":     0,
    "total_anomalies": 0,
    "recent_anomalies": [],   # Last 50 anomalies
    "metric_history": {},     # {metric_key: [float, ...]}
}
_state_lock = threading.Lock()


# ── Background detection loop ─────────────────────────────────────────────────

def _detection_loop() -> None:
    """
    Background thread: polls Prometheus, runs anomaly detection on every
    metric × instance combination, fires alerts and indexes results.
    """
    logger.info(
        "Detection loop started — interval=%ds threshold=%.2f",
        POLL_INTERVAL, ANOMALY_THRESHOLD
    )
    with _state_lock:
        _detection_state["running"] = True

    while _detection_state["running"]:
        try:
            _run_detection_cycle()
        except Exception as exc:
            logger.error("Detection cycle error: %s", exc, exc_info=True)
        time.sleep(POLL_INTERVAL)


def _run_detection_cycle() -> None:
    """Single detection cycle across all monitored metrics."""
    cycle_start = time.monotonic()
    all_metrics = fetch_all_metrics()

    cycle_anomalies = 0

    for metric_def in all_metrics:
        metric_name = metric_def["name"]
        results     = metric_def.get("results", [])

        for result in results:
            instance = result["metric"].get("instance", "unknown")
            try:
                current_value = float(result["value"][1])
            except (IndexError, ValueError, KeyError):
                continue

            key = f"{metric_name}__{instance}"

            with _state_lock:
                history = _detection_state["metric_history"].setdefault(key, [])

            # Need at least 5 data points before detection is meaningful
            if len(history) >= 5:
                anomalies = analyze_metric(metric_name, history + [current_value])

                for anomaly in anomalies:
                    cycle_anomalies += 1
                    _handle_anomaly(anomaly, instance, current_value)

            # Append current value — keep last 120 data points (~1h at 30s interval)
            with _state_lock:
                history.append(current_value)
                if len(history) > 120:
                    history.pop(0)

    elapsed = time.monotonic() - cycle_start
    with _state_lock:
        ML_MONITORED_SERIES.set(
            len(_detection_state["metric_history"])
        )
        _detection_state["last_run"]       = datetime.now(UTC).isoformat()
        _detection_state["total_runs"]    += 1
        _detection_state["total_anomalies"] += cycle_anomalies

    logger.info(
        "Detection cycle complete — %.2fs | %d anomalies detected",
        elapsed, cycle_anomalies
    )


def _handle_anomaly(anomaly: dict, instance: str, current_value: float) -> None:
    """Fire alert to Alertmanager and index to Elasticsearch."""
    metric_name   = anomaly.get("metric_name", "unknown")
    anomaly_score = anomaly.get("anomaly_score", 0.0)
    severity      = "critical" if anomaly_score > 4.0 else "warning"
    
    # Update Prometheus metrics
    ML_ANOMALY_SCORE.labels(
        metric=metric_name,
        instance=instance
    ).set(anomaly_score)
    
    ML_ANOMALIES_TOTAL.inc()

    logger.warning(
        "ANOMALY: %s / %s — score=%.3f severity=%s",
        metric_name, instance, anomaly_score, severity
    )

    # Fire to Alertmanager
    alert_payload = {
        "labels": {
            "alertname":  "InfrastructureAnomalyDetected",
            "severity":   severity,
            "instance":   instance,
            "metric":     metric_name,
            "team":       "aiops",
            "source":     "anomaly-detector",
        },
        "annotations": {
            "summary":     f"Anomaly on {metric_name} for {instance}",
            "description": (
                f"Score {anomaly_score:.3f} exceeds threshold {ANOMALY_THRESHOLD}. "
                f"Current value: {current_value:.2f}"
            ),
        },
        "startsAt": datetime.now(UTC).isoformat(),
    }
    try:
        send_alert(alert_payload)
    except Exception as exc:
        logger.error("Failed to send alert: %s", exc)

    # Index to Elasticsearch
    doc = {
        "@timestamp":   datetime.now(UTC).isoformat(),
        "metric_name":  metric_name,
        "instance":     instance,
        "value":        current_value,
        "anomaly_score": anomaly_score,
        "severity":     severity,
        "detection_method": anomaly.get("detection_method", "composite"),
    }
    try:
        index_anomaly(doc)
    except Exception as exc:
        logger.error("Failed to index anomaly: %s", exc)

    # Store in recent anomalies ring buffer (last 50)
    with _state_lock:
        _detection_state["recent_anomalies"].append({
            **anomaly,
            "instance":  instance,
            "value":     current_value,
            "severity":  severity,
            "timestamp": datetime.now(UTC).isoformat(),
        })
        if len(_detection_state["recent_anomalies"]) > 50:
            _detection_state["recent_anomalies"].pop(0)


# ── FastAPI lifespan — start/stop background thread ──────────────────────────

@asynccontextmanager
async def lifespan(application: FastAPI):
    """Start detection loop on startup, stop gracefully on shutdown."""
    thread = threading.Thread(
        target=_detection_loop,
        name="anomaly-detection-loop",
        daemon=True
    )
    thread.start()
    logger.info("Anomaly detection loop started in background thread")

    yield  # Application is running

    logger.info("Shutting down detection loop...")
    with _state_lock:
        _detection_state["running"] = False


# ── FastAPI app ───────────────────────────────────────────────────────────────

app = FastAPI(
    title="AIOps Anomaly Detection Service",
    description=(
        "Infrastructure anomaly detection using Z-Score, EWMA, and Isolation Forest. "
        "Exposes anomaly scores as Prometheus metrics and fires alerts to Alertmanager."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Mount Prometheus metrics at /metrics
metrics_app = make_asgi_app()
app.mount("/metrics", metrics_app)


# ── Health endpoints ──────────────────────────────────────────────────────────

@app.get("/health/live", tags=["health"])
def liveness():
    """Kubernetes liveness probe — always returns 200 if process is alive."""
    return {"status": "alive", "timestamp": datetime.now(UTC).isoformat()}


@app.get("/health/ready", tags=["health"])
def readiness():
    """
    Kubernetes readiness probe.
    Returns 200 only when Prometheus is reachable and detection loop is running.
    """
    from .prometheus_client import query_prometheus
    try:
        query_prometheus("up")
        prometheus_ok = True
    except Exception:
        prometheus_ok = False

    if not prometheus_ok:
        raise HTTPException(
            status_code=503,
            detail="Prometheus unreachable — service not ready"
        )

    return {
        "status":         "ready",
        "prometheus":     "reachable",
        "detection_loop": "running" if _detection_state["running"] else "stopped",
        "timestamp":      datetime.now(UTC).isoformat(),
    }


# ── Anomaly endpoints ─────────────────────────────────────────────────────────

@app.get("/anomalies", tags=["detection"])
def get_anomalies():
    """Returns the 50 most recent detected anomalies."""
    with _state_lock:
        recent = list(_detection_state["recent_anomalies"])
    return {
        "count":     len(recent),
        "anomalies": recent,
    }


@app.get("/status", tags=["detection"])
def get_status():
    """Returns detection loop status, configuration, and runtime statistics."""
    with _state_lock:
        state = {k: v for k, v in _detection_state.items()
                 if k != "metric_history"}
        metric_keys = list(_detection_state["metric_history"].keys())

    return {
        "status":          "running" if state["running"] else "stopped",
        "last_run":        state["last_run"],
        "total_runs":      state["total_runs"],
        "total_anomalies": state["total_anomalies"],
        "monitored_series": len(metric_keys),
        "config": {
            "poll_interval_seconds": POLL_INTERVAL,
            "anomaly_threshold":     ANOMALY_THRESHOLD,
            "prometheus_url":        PROMETHEUS_URL,
        },
    }


@app.get("/metrics/history/{metric_key}", tags=["detection"])
def get_metric_history(metric_key: str):
    """Returns the raw value history for a given metric__instance key."""
    with _state_lock:
        history = _detection_state["metric_history"].get(metric_key)
    if history is None:
        raise HTTPException(
            status_code=404,
            detail=f"No history found for metric key '{metric_key}'"
        )
    return {
        "metric_key": metric_key,
        "samples":    len(history),
        "values":     history,
    }
